### PR TITLE
Update pro drivers to 2022.11.0

### PR DESCRIPTION
**Pull request by bschwedler**

### CODE REVIEW

**Comment by bschwedler** [comment]
@colearendt  or @samcofer. I don't have permissions to add you as reviewers, but could you take a look please?

**Comment by samcofer** [comment]
Looks good to me, once the build is done I'll approve/merge. Thanks!

**Comment by bschwedler** [comment]
It looks like the Jenkins job doesn't look for PRs from forks: build.posit.it/job/solutions/job/sol-eng-demo-server/ and I don't have permissions to push to a branch in the repo directly.

**Comment by leesahanders** [comment]
Drivers updated and being used in production Colorado with the recent Workbench upgrade: https://github.com/rstudio/sol-eng-kubernetes/pull/264

**Pull request closed without merging**
